repos:
  - repo: local
    hooks:
      - id: swiftlint
        name: SwiftLint
        entry: swiftlint lint --strict
        language: system
        files: \.(swift)$
        pass_filenames: false
        always_run: true
        stages: [pre-commit]
