# ISP Snitch Quality Gates Configuration
# This file defines the minimum quality standards that must be met

quality_standards:
  # Testing Requirements
  testing:
    minimum_test_coverage: 95%
    required_test_suites:
      - ConnectivityRecordTests
      - DatabaseSchemaTests
      - DataStorageTests
      - NetworkIntegrationTests
      - PerformanceOptimizationTests
      - ResourceUsageTests
      - ServiceLifecycleTests
      - StatusCommandTests
      - ReportCommandTests
      - ConfigCommandTests
      - LaunchAgentTests
      - HomebrewTests
      - FileSystemTests
      - PingTests
      - HttpTests
      - DnsTests
      - SpeedtestTests
    
    performance_requirements:
      - "Startup time should be under 5 seconds"
      - "CLI response time should be under 100ms"
      - "Memory usage should be under 50MB baseline"
      - "CPU usage should be under 1% average"
      - "Network overhead should be minimal"
      - "Service should handle concurrent requests efficiently"
      - "Service should maintain performance under load"
      - "Service should recover from errors efficiently"
      - "Service should clean up resources on shutdown"
      - "Service should maintain performance with multiple restarts"
      - "Memory usage should remain stable over time"
      - "CPU usage should remain low during idle"
      - "Service should handle memory pressure gracefully"
      - "Service should handle concurrent access efficiently"
      - "Network monitoring should be efficient"

  # Code Quality Requirements
  code_quality:
    swiftlint_rules:
      - file_length: 300
      - function_body_length: 50
      - type_body_length: 200
      - line_length: 140
      - force_unwrapping: warning
      - force_cast: warning
      - implicitly_unwrapped_optional: warning
    
    architecture_requirements:
      - "No force unwraps in production code"
      - "All actors must be properly isolated"
      - "Repository pattern for data access"
      - "Clean separation of concerns"
      - "Comprehensive error handling"
      - "Safe parsing patterns"

  # Build Requirements
  build_requirements:
    - "Must build successfully with Swift 6.0+"
    - "Must pass all tests (200+ tests)"
    - "Must compile without warnings in production"
    - "Must support both local and CI environments"
    - "Must handle SQLite.swift API consistently"

  # Documentation Requirements
  documentation:
    - "All public APIs must be documented"
    - "Complex business logic must have inline comments"
    - "Architecture decisions must be documented"
    - "API contracts must be clearly defined"

  # Security Requirements
  security:
    - "No hardcoded secrets or credentials"
    - "All user input must be validated"
    - "Database queries must use parameterized statements"
    - "File system access must be properly sandboxed"

  # Performance Requirements
  performance:
    - "Service startup time < 5 seconds"
    - "Memory usage < 50MB baseline"
    - "CPU usage < 1% average"
    - "Network overhead minimal"
    - "Concurrent request handling efficient"
    - "Error recovery efficient"
    - "Resource cleanup on shutdown"
    - "Performance stable over time"

# Quality Gate Enforcement
enforcement:
  pre_commit:
    - "Run swiftlint with strict rules"
    - "Run all tests"
    - "Check for force unwraps"
    - "Validate architecture patterns"
  
  ci_cd:
    - "All tests must pass"
    - "Performance tests must meet thresholds"
    - "Code coverage must be >= 95%"
    - "No critical security issues"
    - "Build must succeed in CI environment"
  
  release:
    - "All quality gates must pass"
    - "Performance benchmarks must be met"
    - "Security scan must pass"
    - "Documentation must be complete"
