# SwiftLint Configuration for ISP Snitch

# Paths to include/exclude
included:
  - Sources
  - Tests

excluded:
  - .build
  - .git
  - dist

# Rules to enable/disable
disabled_rules:
  - todo # Allow TODO comments for development
  - line_length # Allow longer lines for SQL queries and URLs
  - file_length # Allow longer files for database schemas
  - function_body_length # Allow longer functions for database operations
  - type_body_length # Allow longer types for database actors
  - implicit_return # Allow explicit returns for clarity
  - force_unwrapping # Allow force unwrapping in controlled contexts
  - force_cast # Allow force casting in test contexts
  - switch_case_on_newline # Allow compact switch statements
  - empty_count # Allow count comparisons
  - redundant_nil_coalescing # Allow nil coalescing patterns
  - redundant_type_annotation # Allow explicit type annotations
  - large_tuple # Allow larger tuples for database operations
  - unused_closure_parameter # Allow unused parameters in closures
  - identifier_name # Allow short variable names in tests and closures

opt_in_rules:
  - empty_count
  - empty_string
  - explicit_init
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicit_return
  - last_where
  - legacy_random
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - switch_case_on_newline
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - yoda_condition

# Custom rules
line_length:
  warning: 120
  error: 150
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true

file_length:
  warning: 400
  error: 500

function_body_length:
  warning: 50
  error: 100

type_body_length:
  warning: 250
  error: 400

# Identifier naming
identifier_name:
  min_length: 3
  max_length: 40
  excluded:
    - id
    - url
    - uri
    - api
    - db
    - sql
    - json
    - xml
    - csv
    - tcp
    - udp
    - dns
    - http
    - https
    - ssl
    - tls
    - cpu
    - ram
    - gpu
    - ssd
    - hdd
    - ip
    - mac
    - os
    - ui
    - ux
    - cli
    - gui
    - api
    - sdk
    - ios
    - macos
    - tvos
    - watchos

# Force unwrapping rules
force_unwrapping:
  severity: warning

# Force casting rules
force_cast:
  severity: warning

# Implicitly unwrapped optional rules
implicitly_unwrapped_optional:
  severity: warning

# Large tuple rules
large_tuple:
  warning: 2
  error: 3

# Unused closure parameter rules
unused_closure_parameter:
  severity: warning
