# SwiftLint Configuration for ISP Snitch

# Paths to include/exclude
included:
  - Sources
  # - Tests  # Exclude tests from linting - they need comprehensive coverage

excluded:
  - .build
  - .git
  - dist
  - Tests  # Don't lint test files - they need to be comprehensive

# Length rules for source code only
file_length:
  warning: 300
  error: 500

function_body_length:
  warning: 50
  error: 80

type_body_length:
  warning: 200
  error: 300

# Force unwraps and casts → warnings only
force_unwrapping:
  severity: warning

force_cast:
  severity: warning

# Rules to disable entirely
disabled_rules:
  - todo # Allow TODOs in dev
  - switch_case_on_newline # Allow compact switches
  - redundant_nil_coalescing
  - redundant_type_annotation
  - identifier_name # We'll handle with custom rules instead

# Rules enabled with warnings (more relaxed enforcement)
opt_in_rules:
  - empty_count
  - empty_string
  - explicit_init
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicit_return
  - last_where
  - legacy_random
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - single_test_class
  - sorted_first_last
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - yoda_condition

# Relaxed length rules
line_length:
  warning: 140
  error: 180
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true

# Length rules are defined above with test exclusions

# Identifier naming
identifier_name:
  min_length: 2
  max_length: 50
  excluded:
    - id
    - url
    - uri
    - api
    - db
    - sql
    - json
    - xml
    - csv
    - tcp
    - udp
    - dns
    - http
    - https
    - ssl
    - tls
    - cpu
    - ram
    - gpu
    - ssd
    - hdd
    - ip
    - mac
    - os
    - ui
    - ux
    - cli
    - gui
    - sdk
    - ios
    - macos
    - tvos
    - watchos

# Force unwraps and casts → warnings only (defined above with test exclusions)

implicitly_unwrapped_optional:
  severity: warning

# Large tuple rules (relaxed)
large_tuple:
  warning: 3
  error: 5

# Unused closure parameter rules → warning only
unused_closure_parameter:
  severity: warning