name: CI/CD (Swift)

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  # Cut a release by tagging vX.Y.Z
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: read
  security-events: write

env:
  SWIFT_VERSION: "6.0"

jobs:
  build_test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: swift-actions/setup-swift@v2.3.0
        with: { swift-version: ${{ env.SWIFT_VERSION }} }
      - uses: actions/cache@v4
        with:
          path: |
            ~/.swiftpm
            ~/Library/Caches/org.swift.swiftpm
          key: ${{ runner.os }}-spmcache-${{ hashFiles('**/Package.resolved') }}
          restore-keys: ${{ runner.os }}-spmcache-
      - run: swift package resolve
      - run: swift build --configuration debug
      - run: swift test --parallel

  lint:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: realm/SwiftLint@5.0.0
        with: { strict: true }

  security:
    if: github.event_name == 'pull_request' && startsWith(github.base_ref, 'main')
    needs: [build_test]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Trivy FS scan
        uses: aquasecurity/trivy-action@v0.20.0
        with:
          scan-type: fs
          scan-ref: .
          format: sarif
          output: trivy-results.sarif
      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v3
        with: { sarif_file: trivy-results.sarif }

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [build_test, lint]
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: swift-actions/setup-swift@v2.3.0
        with: { swift-version: ${{ env.SWIFT_VERSION }} }
      - run: swift build --configuration release
      - name: Package artifact
        run: |
          mkdir -p dist
          cp .build/release/isp-snitch dist/
          tar -czf dist/isp-snitch-${GITHUB_REF_NAME}.tar.gz -C dist isp-snitch
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: isp-snitch-${{ github.ref_name }}
          path: dist/
      - name: Attach to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/isp-snitch-${{ github.ref_name }}.tar.gz