name: Dependabot Auto-merge

on:
  pull_request:
    types: [opened, approved, synchronize]

jobs:
  auto-merge:
    name: Auto-merge Dependabot PRs
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    
    steps:
    - name: Enable auto-merge
      run: |
        gh pr merge --auto --squash "${{ github.event.pull_request.number }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
